branches:
  only:
  - master
language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: test
      install:
        - npm install
      script:
        - npm run build
        - npm test
    - stage: deploy
      if: type = push
      install:
        - echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
        - npm install
      script:
        - npm run deploy
