branches:
  only:
  - master
language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
before_install:
- echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
install: npm install
script: npm run deploy
